runtime:
  cache_dir: ./.cache/antora

site:
  title: OpenShift Starter Guides
  url: http://redhat-scholars.github.io/openshift-starter-guides/
  start_page: rhs-openshift-starter-guides::index.adoc

content:
  sources:
    - url: git@github.com:redhat-scholars/openshift-starter-guides.git
      tags: []
      branches: [ocp-4.7, ocp-4.8, ocp-4.9]
      start_path: documentation

asciidoc:
  attributes:
    project-namespace: workshop
  extensions:
    - ./lib/tab-block.js
    - ./lib/remote-include-processor.js

ui:
  bundle:
    url: https://github.com/redhat-scholars/course-ui/releases/download/v0.1.8/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./gh-pages
